config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root 'home#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized to edit this friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group" >
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class: "form-control", placeholder: "First Name" %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div>
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter, class: "form-control" %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id, id: :friend_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>
  
  <div>
    <%= form.submit class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
  <div id="<%= dom_id friend %>">
    <td>
      <%= friend.first_name %>
      <%= friend.last_name %>
    </td>
    <td><%= friend.email %></td>
    <td><%= friend.phone %></td>
    <td><%= friend.twitter %></td>
    <td><%= friend.user_id %></td>
  </div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class: "btn btn-secondary" %> |
  <%= link_to "Back to friends", friends_path, class: "btn btn-secondary" %>
</div>

app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="friends">
  <table class="table table-striped table-bordered">
    <thead class="table-dark">
      <tr >
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col">Phone</th>
        <th scope="col">Twitter</th>
        <th scope="col">User Id</th>
        <th colspan="2"></th>

      </tr>
    </thead>
    <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user %>
          <tr>
            <%= render friend %>
            <td><%= link_to "Show this friend", friend, class: "btn btn-secondary" %></td>
            <td><%= link_to "Edit this friend", edit_friend_path(friend), class: "btn btn-secondary" %></td>
            <td><%= button_to "Destroy this friend", friend, method: :delete, class: "btn btn-secondary" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to "New friend", new_friend_path, class: "btn btn-secondary" %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class: "btn btn-secondary" %>
</div>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>
<table class="table table-striped table-bordered">
  <thead class="table-dark">
    <tr >
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Twitter</th>
      <th scope="col">User Id</th>
      <th colspan="2" ></th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <%= render @friend %>
        <td><%= link_to "Edit this friend", edit_friend_path(@friend), class: "btn btn-secondary" %></td>
        <td><%= button_to "Destroy this friend", @friend, method: :delete, class: "btn btn-secondary" %></td>
      </tr>
  </tbody>
</table>

<div>
  <%= link_to "Back to friends", friends_path, class: "btn btn-secondary" %>
</div>

app/views/home/_footer.html.erb
Footer

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "User's Accounts", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "Home", root_path, class: "nav-link" %>
        <%= link_to "About", home_about_path, class: "nav-link" %>
        <%= link_to "Friends", friends_path, class: "nav-link" %>
        <%= link_to "Add Friend", new_friend_path, class: "nav-link" %>
        <% if user_signed_in? %>
          <%= link_to "Add Friend", new_friend_path, class: "nav-link" %>
          <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link"  %>
          <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        <% end %>


      </div>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning text-center container" role="alert">
  <strong><%= notice %></strong>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UsersAccounts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'home/header' %>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    <div class="container" >
      <%= yield %>
    </div>
    <%= render 'home/footer' %>
  </body>
</html>